# Generated by Django 4.0.5 on 2022-06-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rightanswer_useranswer_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightanswer',
            name='flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выбор варианта'),
        ),
        migrations.AddField(
            model_name='rightanswer',
            name='type',
            field=models.CharField(choices=[('P1', '1 правильный ответ'), ('P2', 'Множественный выбор'), ('REL', 'Соответствие'), ('STR', 'Текстовые пункты')], default='STR', max_length=4, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='solved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solved_questions', to=settings.AUTH_USER_MODEL, verbose_name='Решено пользователем'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выбор варианта'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='type',
            field=models.CharField(choices=[('P1', '1 правильный ответ'), ('P2', 'Множественный выбор'), ('REL', 'Соответствие'), ('STR', 'Текстовые пункты')], default='STR', max_length=4, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='rightanswer',
            name='label',
            field=models.TextField(null=True, verbose_name='Вариант или название пункта'),
        ),
        migrations.AlterField(
            model_name='rightanswer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовый ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='label',
            field=models.TextField(null=True, verbose_name='Вариант или название пункта'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовый ответ'),
        ),
    ]
