# Generated by Django 4.0.6 on 2022-07-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_basequestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='listed',
            field=models.BooleanField(default=True, verbose_name='Публичный доступ'),
        ),
    ]
