# Generated by Django 4.0.5 on 2022-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rightanswer_flag_rightanswer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basequestion',
            name='style',
        ),
        migrations.RemoveField(
            model_name='rightanswer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='type',
        ),
        migrations.AddField(
            model_name='basequestion',
            name='type',
            field=models.CharField(choices=[('P1', '1 правильный ответ'), ('P2', 'Множественный выбор'), ('REL', 'Соответствие'), ('STR', 'Текстовые пункты')], default='STR', max_length=4, verbose_name='Тип'),
        ),
    ]
