# Generated by Django 4.0.6 on 2022-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_basequestion_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.AddField(
            model_name='question',
            name='number_10',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер в 10 классе'),
        ),
        migrations.AddField(
            model_name='question',
            name='number_11',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер в 11 классе'),
        ),
        migrations.AddField(
            model_name='question',
            name='number_9',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер в 9 классе'),
        ),
    ]
