# Generated by Django 4.0.6 on 2022-07-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_question_number_question_number_10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightanswer',
            options={'ordering': ['parent_question', 'label'], 'verbose_name': 'Вариант или пункт', 'verbose_name_plural': 'Вариант или пункт'},
        ),
    ]
