# Generated by Django 4.0.5 on 2022-06-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_basequestion_style_remove_rightanswer_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Вопрос с олимпиады', 'verbose_name_plural': 'Вопросы с олимпиад'},
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.imagealbum', verbose_name='Набор изображений'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images/', verbose_name='Файл'),
        ),
    ]
