# Generated by Django 4.0.5 on 2022-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_question_options_alter_image_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequestion',
            name='max_points',
            field=models.IntegerField(null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='rightanswer',
            name='is_right',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выбор варианта'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='user_points',
            field=models.IntegerField(null=True, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='user_score',
            field=models.FloatField(default=0.0, null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='user_text',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
    ]
