# Generated by Django 4.0.6 on 2022-08-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.competition', verbose_name='Олимпиада')),
                ('sections', models.ManyToManyField(blank=True, related_name='%(class)s', to='main.section', verbose_name='Разделы')),
                ('topics', models.ManyToManyField(blank=True, related_name='%(class)s', to='main.topic', verbose_name='Темы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testquestion',
            name='parent_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test', verbose_name='Тест'),
        ),
    ]
