# Generated by Django 4.0.5 on 2022-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_basequestion_max_points_rightanswer_is_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightanswer',
            name='is_right',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_right',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выбор варианта'),
        ),
    ]
