# Generated by Django 4.0.6 on 2022-08-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_test_testquestion_parent_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['title'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
