# Generated by Django 4.0.5 on 2022-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_rightanswer_is_right_useranswer_is_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basequestion',
            name='max_points',
            field=models.IntegerField(default=4, null=True, verbose_name='Количество ответов'),
        ),
    ]
