# Generated by Django 4.0.5 on 2022-06-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_basequestion_max_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basequestion',
            name='max_points',
        ),
    ]
