# Generated by Django 4.0.6 on 2022-08-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_test_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['parent_test', 'title'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы тетов'},
        ),
    ]
