# Generated by Django 4.0.5 on 2022-06-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_basequestion_max_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightanswer',
            options={'ordering': ['parent_question'], 'verbose_name': 'Вариант или пункт', 'verbose_name_plural': 'Вариант или пункт'},
        ),
    ]
