# Generated by Django 4.1.3 on 2022-12-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_testquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['parent_test', 'title'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы тестов'},
        ),
    ]
