# Generated by Django 4.0.5 on 2022-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_rightanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequestion',
            name='answers_num',
            field=models.IntegerField(default=4, null=True, verbose_name='Количество вариантов или пунктов'),
        ),
    ]
