# Generated by Django 4.0.5 on 2022-06-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_basequestion_answers_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basequestion',
            name='answers_num',
        ),
    ]
