# Generated by Django 4.1.3 on 2022-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_competition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_others',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер для других классов'),
        ),
    ]
