# Generated by Django 4.1.3 on 2022-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_competition_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.CharField(default='Заключительный', max_length=100, verbose_name='Этап'),
        ),
    ]
