# Generated by Django 4.1.3 on 2022-12-09 22:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_question_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(default='Заключительный', max_length=100, verbose_name='Этап')),
                ('slug', models.SlugField(default='zakl', validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('competition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.competition', verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['competition', 'name'],
            },
        ),
    ]
