# Generated by Django 4.1.3 on 2022-12-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_stage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.newstage', verbose_name='Этап'),
        ),
    ]
