# Generated by Django 4.1.3 on 2022-12-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_question_new_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='stage',
        ),
    ]
