# Generated by Django 4.1.3 on 2023-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_by",
                to="main.basequestion",
                verbose_name="Сохраненные вопросы",
            ),
        ),
    ]
