# Generated by Django 4.1.3 on 2023-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_remove_profile_saved_questions_basequestionsave"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_by",
                through="main.BaseQuestionSave",
                to="main.basequestion",
                verbose_name="Сохраненные вопросы",
            ),
        ),
    ]
