# Generated by Django 4.1.3 on 2023-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_profile_saved_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="variant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Вариант"
            ),
        ),
    ]
