# Generated by Django 4.1.3 on 2023-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_rightanswer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_flag_selected',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_text',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_right',
            field=models.BooleanField(blank=True, null=True, verbose_name='Верный ответ'),
        ),
    ]
