# Generated by Django 4.1.3 on 2023-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_useranswer_user_flag_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedquestion',
            name='user_points',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество верных ответов'),
        ),
    ]
